# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'LiveApp' do
  use_frameworks!
pod 'Kingfisher', '~> 3.2.1' 
pod 'Alamofire', '~> 4.2.0'
pod 'LFLiveKit'	
end
